[workspace]
channels = ["conda-forge"]
name = "bibliomania"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
create_db = "touch openalex_local.db && rm openalex_local.db && python -s smart_ingest.py"

[dependencies]
python = "3.13.*,<3.14"

[pypi-dependencies]
boto3 = ">=1.42.0, <2"
torch = ">=2.9.1, <3"
duckdb = ">=1.4.2, <2"
fastapi = ">=0.123.0, <0.124"
uvicorn = ">=0.38.0, <0.39"
transformers = ">=4.51.3, <5"
adapters = ">=1.2.0, <2"
numpy = ">=2.3.5, <3"
scikit-learn = ">=1.7.2, <2"
networkx = ">=3.6, <4"
